### ISSUE TITLE
blocks3d's website doesnt work

### ISSUE THREAD

**Issue by SilvazWasTaken** [andreja6/G3D-Fun#106] opened 2022-10-07 15:34 UTC
![image](https://user-images.githubusercontent.com/112694330/194592455-85fa4028-d2cf-41f1-bf70-55542f1dccd4.png)
idk if this is intentional or not

**Comment by himdeez** [comment] 2022-10-07 18:30
this issue is a duplicate of #68

**Closed as completed** 2022-10-26 05:24 UTC
Labels: duplicate
